// 메세지 생성
###
POST localhost:8080/messages
Content-Type: application/json

{
    "content": "Hello, World!"
}
###

// 메세지 조회
@messageId=1
###
GET localhost:8080/messages/{{messageId}}
###

// 전체 메세지 조회
###
GET localhost:8080/messages
###
