
@SLACK_WEBHOOK_URL = https://slack.com/api/chat.postMessage
@SLACK_TOKEN = xoxb
@SLACK_CHANNEL = channel-id

###
POST {{SLACK_WEBHOOK_URL}}
Authorization: Bearer {{SLACK_TOKEN}}
Content-Type: application/json

{
  "channel": "{{SLACK_CHANNEL}}",
  "text": "Hello, Slack!"
}

###
