@host = localhost:9000

###
POST {{host}}/api/timetables
Content-Type: application/json

{
  "schoolId": 21,
  "department": "소프트웨어학부",
  "grade": 2,
  "majorRequiredCourses": [
    "자료구조"
  ],
  "majorElectiveCourses": [
    "컴퓨터구조",
    "객체지향프로그래밍및실습",
    "선형대수"
  ],
  "generalRequiredCourses": [
    "[글로벌소통과언어]CTE for IT, Engineering&Natura"
  ],
  "majorElectiveCredit": 9,
  "generalElectiveCredit": 6,
  "chapel": true
}
###




@timeTableId = 10000
###
GET {{host}}/api/timetables/{{timeTableId}}
Content-Type: application/json

###