@host = localhost:9000

###
POST {{host}}/api/timetables
Content-Type: application/json

{
  "schoolId": 21,
  "department": "컴퓨터학부",
  "grade": 1,
  "isChapel": true,
  "majorRequiredCourses": [],
  "majorElectiveCourses": [],
  "generalRequiredCourses": [],
  "majorElectiveCredit": 9,
  "generalElectiveCredit": 5
}

###
